[package]
name = "converge_example_flexible"
version = "0.0.6"
authors = ["Owen Synge <osynge@googlemail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
resolver = "3"
description = """Flexible example for `converge::Converge` trait and the
`converge_derive` proc-macro."""
repository = "https://github.com/osynge/converge"
keywords = ["config", "converge", "merge", "derive", "configuration"]
readme = "../../README.md"
include = ["src/**/*.rs", "crates-io.md", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
categories = ["data-structures", "config"]

[dependencies]
converge = { version = "0.0.6", path = "../../converge" }
converge_derive = { version = "0.0.6", path = "../../converge_derive" }
pretty_assertions = "1"
clap = { version = "4.6.7", features = ["cargo"] }
toml = "1.1.6"
serde = "1.0.229"
serde_derive = "1.0.229"
thiserror = "2.0.21"
dirs = "7.0.0"
